
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-ops
  namespace: production
  labels:
    dep: bill-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      dep: bill-ops
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      name: bill-ops
      labels:
        dep: bill-ops
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/cloudverse-au/prod/platform-bill-ops@sha256:97533371859eca719de029612ec4cafa44476dc2148dab35bbec7a49c2b54365
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "25m"
            memory: "50Mi"
        envFrom:
        - secretRef:
            name: production-common-secret
        - secretRef:
            name: production-bill-ops
        volumeMounts:
        - name: gcp-creds
          mountPath: /app/gcp_credentials.json
          subPath: gcp_credentials.json
      volumes:
      - name: gcp-creds
        secret:
          secretName: production-cloud-provider-driver-gcp-credentials-secret
