apiVersion: v1
kind: Service
metadata:
  name: xchange-rate-svc
  namespace: production
  labels:
    service: production-xchange-rate
spec:
  selector:
    dep: production-xchange-rate
  type: NodePort
  ports:
  - port: 5444
    targetPort: 5444
