apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-cloud-discovery-v2
  namespace: production
  labels:
    dep: production-cloud-discovery-v2

spec:
  replicas: 0
  selector:
    matchLabels:
      dep: production-cloud-discovery-v2
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      namespace: production
      name: production-cloud-discovery-v2
      labels:
        dep: production-cloud-discovery-v2
    spec:
      topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                dep: production-cloud-provider-discovery
      tolerations:
      - key: app
        operator: Equal
        value: discovery
        effect: NoSchedule
      containers:
      - name: production-cloud-discovery-v2
        image: asia-southeast1-docker.pkg.dev/cloudverse-foundation/prod/external-endpoint@sha256:24acb19309e7d2a0a87110d916f90bc84710460d90d468169982a1c1062e042d
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2
            memory: 1G
          limits:
            cpu: 1
            memory: 1Gi
        # readinessProbe:
        #   httpGet:
        #     path: /health-check
        #     port: 8000
        #   initialDelaySeconds: 3
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /health-check
        #     port: 8000
        #   initialDelaySeconds: 3
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        volumeMounts:
        - name: production-cloud-discovery-v2-aws-credentials-secret
          mountPath: /root/.aws/credentials
          subPath: credentials
        - name: production-cloud-discovery-v2-gcp-credentials-secret
          mountPath: /app/gcp_credentials.json
          subPath: gcp_credentials.json
        - name: looker
          mountPath: /app/looker.ini
          subPath: looker.ini
        - name: oci
          mountPath: /app/oci_api_key.pem
          subPath: oci_api_key.pem
        - name: oci
          mountPath: /app/oci_api_key_public.pem
          subPath: oci_api_key_public.pem
        envFrom:
        - secretRef:
            name: production-common-secret
        - secretRef:
            name: production-cloud-discovery-v2-secret
      volumes:
      - name: production-cloud-discovery-v2-aws-credentials-secret
        secret:
          secretName: production-cloud-provider-driver-aws-credentials-secret
      - name: production-cloud-discovery-v2-gcp-credentials-secret
        secret:
          secretName: production-cloud-provider-driver-gcp-credentials-secret
      - name: looker
        secret:
          secretName: looker
      - name: oci
        secret:
          secretName: production-oci-api-key
