apiVersion: v1
kind: Service
metadata:
  name: production-cloud-discovery-v2
  namespace: production
  labels:
    service: production-cloud-discovery-v2
spec:
  selector:
    dep: production-cloud-discovery-v2
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
