
apiVersion: v1
kind: Service
metadata:
  name: production-cspm
  namespace: production
  labels:
    service: production-cspm
spec:
  selector:
    dep: production-cspm
  type: ClusterIP
  ports:
  - port: 3090
    targetPort: 3090
