apiVersion: v1
kind: Service
metadata:
  name: predective-cost-system-prod
  labels:
    app: predective-cost-system-prod
spec:
  selector:
    app: predective-cost-system-prod
  type: LoadBalancer
  ports:
    - name: fastapi
      port: 8000
      targetPort: 8000
    - name: mlflow
      port: 5000
      targetPort: 5000
