
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-genai-insights
  namespace: production
  labels:
    dep: production-genai-insights
    app.kubernetes.io/instance: production-genai-insights 
spec:
  replicas: 1
  selector:
    matchLabels:
      dep: production-genai-insights
      app.kubernetes.io/instance: production-genai-insights 
  template:
    metadata:
      labels:
        dep: production-genai-insights
        app.kubernetes.io/instance: production-genai-insights 
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/cloudverse-au/prod/genai-insights@sha256:76147c01a65d83e78deca39da18717f63f5360c1e9f4c7d4ce0c07e25b1ddd39
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: prod-genai-insights-prod
