
apiVersion: v1
kind: Service
metadata:
  name: cv-gpt-driver-svc
  namespace: production
  labels:
    service: production-cv-gpt-driver
spec:
  selector:
    dep: production-cv-gpt-driver
  type: NodePort
  ports:
  - port: 5555
    targetPort: 5555
