apiVersion: v1
kind: Service
metadata:
  name: cv-data-transform
  labels:
    service: cv-data-transform
spec:
  selector:
    dep: cv-data-transform
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
