apiVersion: v1
kind: Service
metadata:
  name: cv-integration-connector
  labels:
    service: cv-integration-connector
spec:
  selector:
    dep: cv-integration-connector
  type: LoadBalancer
  ports:
    - port: 3000  
      targetPort: 3000
